### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by yqian1991** [omniti-labs/jlog#23]
I used autoconf to generate the Makefile, but find some bugs in it:

```
install-python:
	cd python && make install

clean:
	rm -f *.o *.lo *.$(DOTSO) *.a jthreadtest jtest jlogctl jlogtail
	rm -f java/*.jar java/*.jnilib java/*.lo
	-if test -f perl/Makefile ; then cd perl ; make clean ; fi
	cd python && make clean
```

can we really run ```make``` command in the python folder?

**Comment by postwait** [comment]
Works for me.  Please open a new ticket with the error message you get from running make.
